# Overrides output stereo position (reverse)

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
         audio.position = ["FR", "FL"]
      }
    }
  }
]