daemon off;
error_log /dev/stdout info;
events { }

http {
		access_log /dev/stdout;
    include /usr/local/openresty/nginx/conf/mime.types;
    server {
        listen localhost:8000;
        root ../;
        location / {
          autoindex on;
        }
    }
}
