include ./theme.conf

update_check_interval 0

term xterm-256color

enable_audio_bell false

macos_titlebar_color background
wayland_titlebar_color background

tab_bar_edge top
tab_bar_style slant
active_tab_font_style   bold
inactive_tab_font_style normal
inactive_text_alpha 0.85

font_size 20.0

cursor_shape block
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

#cursor_blink_interval 0
#cursor_stop_blinking_after 15.0

kitty_mod ctrl+shift

macos_option_as_alt both
# Use Alt/Meta + arrows to navigate between words
# Disabled. Let .zshrc handle it
#map alt+left send_text all \x1b\x62
#map alt+right send_text all \x1b\x66

map kitty_mod+escape kitty_shell window

macos_quit_when_last_window_closed yes

map kitty_mod+t launch --type=tab --cwd=current
map cmd+t launch --type=tab --cwd=current

map cmd+w close_window

enabled_layouts splits,stack
map cmd+d        launch --type=window --location=vsplit --cwd=current
map cmd+shift+d  launch --type=window --location=hsplit --cwd=current

map kitty_mod+n  launch --type=os-window --cwd=current
map cmd+n  launch --type=os-window --cwd=current

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard
copy_on_select   yes

mouse_map left click ungrabbed no-op
mouse_map ctrl+left press ungrabbed,grabbed kitten hints

